# Generated by Django 4.2.3 on 2023-07-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='courses', to='materials.material'),
        ),
    ]
